//generate from typed-css-modules
//link : https://github.com/Quramy/typed-css-modules
declare const styles: {
  readonly 'ecommerce-ad-container': string
  readonly 'ecommerce-ad': string
  readonly 'ecommerce-ad-img': string
  readonly 'ecommerce-ad-main': string
  readonly 'ecommerce-ad-main-content': string
  readonly 'ecommerce-ad-main-content-price': string
  readonly 'ecommerce-ad-main-content-des': string
  readonly 'ecommerce-ad-main-content-title': string
  readonly 'ecommerce-ad-main-content-title-logo': string
  readonly 'ecommerce-ad-icon': string
  readonly Button: string
  readonly 'Button--grey': string
  readonly 'Button--blue': string
  readonly 'Button--green': string
  readonly 'Button--red': string
  readonly 'Button--primary': string
  readonly 'Button--secondary': string
  readonly 'Button--link': string
  readonly 'Button--plain': string
  readonly 'Button--spread': string
  readonly 'Button--withIcon': string
  readonly 'Button--iconOnly': string
  readonly 'Button--withLabel': string
  readonly 'Button-zi': string
  readonly 'ModalButtonGroup--vertical': string
  readonly 'Modal-content--buttonGroupOnly': string
  readonly 'ModalButtonGroup--horizontal': string
  readonly 'Modal-wrapper': string
  readonly 'Modal-enter': string
  readonly 'Modal-enter-active': string
  readonly 'Modal-leave': string
  readonly 'Modal-leave-active': string
  readonly 'Modal-backdrop': string
  readonly 'Modal-wrapper--transparent': string
  readonly Modal: string
  readonly 'Modal--large': string
  readonly 'Modal--fullPage': string
  readonly 'Modal-inner': string
  readonly 'Modal-closeButton': string
  readonly 'Modal-closeIcon': string
  readonly 'Modal-title': string
  readonly 'Modal-title--simple': string
  readonly 'Modal-subtitle': string
  readonly 'Modal-content': string
  readonly 'Modal-content--spread': string
  readonly 'Modal-content--hidden': string
  readonly 'Modal-footer': string
  readonly Notification: string
  readonly 'Notification-textSection': string
  readonly 'Notification-textSection--withButton': string
  readonly 'Notification-textSection--withoutButton': string
  readonly 'Notification-actionsSection': string
  readonly 'Notification-wrapper': string
  readonly 'Notification-white': string
  readonly 'Notification-red': string
  readonly 'Notification-red-ghost': string
  readonly 'Notification-enter': string
  readonly 'spring-in': string
  readonly 'Notification-leave': string
  readonly 'spring-out': string
  readonly Icon: string
  readonly 'Icon--grey': string
  readonly 'Icon--left': string
  readonly 'MobileModal-wrapper': string
  readonly 'MobileModal-wrapper--absoluted': string
  readonly MobileModal: string
  readonly 'MobileModal-content--default': string
  readonly 'MobileModal-closeButton': string
  readonly 'MobileModal-closeIcon': string
  readonly 'MobileModal-title': string
  readonly 'MobileModal-title--default': string
  readonly 'MobileModal-backdrop': string
  readonly 'MobileModal--plain': string
  readonly 'MobileModal-content--plain': string
  readonly 'MobileModal-title--plain': string
  readonly 'MobileModal-subtitle': string
  readonly 'AppAuthentication--appView': string
  readonly AppAuthentication: string
  readonly 'AppAuthentication-buttonContainer': string
  readonly 'AppAuthentication-button': string
  readonly 'AppAuthentication-closeButton': string
  readonly SignFlow: string
  readonly 'SignFlow-accountInput': string
  readonly 'SignFlow-smsInput': string
  readonly 'SignFlow-submitButton': string
  readonly 'SignFlow-captchaContainer': string
  readonly 'SignFlow-snackBar': string
  readonly 'SignFlow-snackBarLink': string
  readonly UnknownError: string
  readonly CornerButtons: string
  readonly CornerAnimayedFlex: string
  readonly 'CornerAnimayedFlex--hidden': string
  readonly CornerButton: string
  readonly Zi: string
  readonly ErrorPage: string
  readonly 'ErrorPage-container': string
  readonly 'ErrorPage-subtitle': string
  readonly 'ErrorPage-title': string
  readonly 'ErrorPage-text': string
  readonly 'ErrorPage-primaryButton': string
  readonly 'ErrorPage-errorImageContainer': string
  readonly RetryError: string
  readonly 'RetryError-title': string
  readonly Popover: string
  readonly 'Popover-arrow': string
  readonly 'Popover-arrow--top': string
  readonly 'Popover-arrow--bottom': string
  readonly 'Popover-arrow--left': string
  readonly 'Popover-arrow--right': string
  readonly 'Popover-content': string
  readonly 'Popover-content-enter': string
  readonly 'Popover-content-enter-active': string
  readonly 'Popover-content-leave': string
  readonly 'Popover-content-leave-active': string
  readonly 'Popover-content--fixed': string
  readonly 'Popover-content--top': string
  readonly 'Popover-content--arrowed': string
  readonly 'Popover-content--enter': string
  readonly 'Popover-content--bottom': string
  readonly 'Popover-content--left': string
  readonly 'Popover-content--right': string
  readonly AttentionPopover: string
  readonly 'Select-button': string
  readonly 'Select-plainButton': string
  readonly 'Select-arrow': string
  readonly 'Select-list': string
  readonly 'Select-option': string
  readonly 'Select-popoverTarget': string
  readonly 'Input-wrapper': string
  readonly 'Input-wrapper--grey': string
  readonly 'Input-wrapper--spread': string
  readonly 'Input-wrapper--multiline': string
  readonly 'Input-wrapper--large': string
  readonly 'RichText--editable': string
  readonly 'Dropzone-overlay': string
  readonly 'Input-wrapper--noPadding': string
  readonly 'is-focus': string
  readonly Input: string
  readonly 'public-DraftEditorPlaceholder-root': string
  readonly 'Input--validationError': string
  readonly 'Input-after': string
  readonly VerificationDialogModalHeader: string
  readonly 'VerificationDialogModalHeader-title': string
  readonly 'VerificationDialogModalHeader-subTitle': string
  readonly 'VerificationDialogModal-select': string
  readonly 'VerificationDialogModal-code': string
  readonly CountingDownButton: string
  readonly 'VerificationDialogModal-input': string
  readonly 'VerificationDialogModal-checkout': string
  readonly 'VerificationDialogModal-button': string
  readonly 'VerificationDialogModal-tips': string
  readonly 'VerificationDialogModal-blue': string
  readonly 'Popover-targetContainer-verification': string
  readonly 'VerificationDialogModal-options': string
  readonly 'VerificationDialogModal-cutSmsType': string
  readonly 'VerificationDialogModal-HelpWrapper': string
  readonly 'VerificationDialogModal-HelpText': string
  readonly 'VerificationDialogMobileModal-HelpText': string
  readonly 'VerificationDialogModal-oneSelection': string
  readonly 'VerificationDialogModal-smsInputButton': string
  readonly Tooltip: string
  readonly 'Tooltip-enter': string
  readonly 'Tooltip-leave': string
  readonly 'Tooltip-enter-active': string
  readonly 'Tooltip-leave-active': string
  readonly 'TooltipContent-wrapper': string
  readonly TooltipContent: string
  readonly 'TooltipContent--white': string
  readonly 'TooltipContent-arrow': string
  readonly 'TooltipContent--top': string
  readonly 'TooltipContent--bottom': string
  readonly 'TooltipContent--left': string
  readonly 'TooltipContent--right': string
  readonly 'TooltipContent-children--restricted': string
  readonly GlobalTooltip: string
  readonly WechatShareImage: string
  readonly StaticCacheBanner: string
  readonly LoadingBar: string
  readonly 'is-active': string
  readonly LoadingBarForward: string
  readonly ShortcutHintModal: string
  readonly 'ShortcutHintModal-content': string
  readonly 'ShortcutHintModal-hintListContainer': string
  readonly 'ShortcutHintModal-hintList': string
  readonly 'ShortcutHintModal-hintTitle': string
  readonly KeyHint: string
  readonly 'KeyHint-keyContainer': string
  readonly 'KeyHint-key': string
  readonly 'KeyHint-separator': string
  readonly 'KeyHint-separator--space': string
  readonly 'KeyHint-kbd': string
  readonly Sticky: string
  readonly 'is-fixed': string
  readonly 'is-absolute': string
  readonly 'is-bottom': string
  readonly 'Sticky--CSSSticky': string
  readonly 'Sticky--holder': string
  readonly Tabs: string
  readonly 'Tabs-item': string
  readonly 'Tabs-link': string
  readonly 'Tabs-meta': string
  readonly ZhihuLogo: string
  readonly 'ZhihuLogo--grey': string
  readonly 'ZhihuLogo--red': string
  readonly 'ZhihuLogo--green': string
  readonly OrgZhihuLogo: string
  readonly 'OrgZhihuLogo-appName': string
  readonly OrgAppHeader: string
  readonly 'OrgAppHeader-inner': string
  readonly 'is-hidden': string
  readonly 'OrgAppHeader-userInfo': string
  readonly Menu: string
  readonly 'Menu-item': string
  readonly 'Menu-item--noActive': string
  readonly 'Menu-divider': string
  readonly EmptyState: string
  readonly 'EmptyState-inner': string
  readonly 'EmptyState-image': string
  readonly 'EmptyState-action': string
  readonly BounceLoading: string
  readonly 'BounceLoading-child': string
  readonly Bounce: string
  readonly 'InfiLoader--bounceShown': string
  readonly 'PlaceHolder-inner': string
  readonly 'PlaceHolder-mask': string
  readonly 'PlaceHolder-bg': string
  readonly 'linear-double': string
  readonly OpenInAppButton: string
  readonly 'is-shown': string
  readonly ztext: string
  readonly external: string
  readonly internal: string
  readonly 'ztext-link': string
  readonly ellipsis: string
  readonly invisible: string
  readonly member_mention: string
  readonly 'ztext-empty-paragraph': string
  readonly content_image: string
  readonly origin_image: string
  readonly 'zh-lightbox-thumb': string
  readonly 'ztext-referene-tooltip': string
  readonly 'TooltipContent-children': string
  readonly 'link-box': string
  readonly 'video-box': string
  readonly thumbnail: string
  readonly content: string
  readonly title: string
  readonly url: string
  readonly label: string
  readonly Avatar: string
  readonly 'Avatar--medium': string
  readonly 'Avatar--large': string
  readonly 'Avatar--round': string
  readonly NumberBoard: string
  readonly 'NumberBoard--divider': string
  readonly 'NumberBoard-item': string
  readonly 'NumberBoard-itemInner': string
  readonly 'NumberBoard-itemName': string
  readonly 'NumberBoard-itemValue': string
  readonly 'NumberBoard-itema': string
  readonly 'HoverCard-coverContainer': string
  readonly 'HoverCard-cover': string
  readonly 'HoverCard-subtitle': string
  readonly 'HoverCard-title': string
  readonly 'HoverCard-titleContainer': string
  readonly 'HoverCard-titleContainer--noAvatar': string
  readonly 'HoverCard-avatar': string
  readonly 'HoverCard-titleText': string
  readonly 'HoverCard-attrInfo': string
  readonly HoverCard: string
  readonly 'HoverCard--isLoading': string
  readonly 'HoverCard-loading': string
  readonly 'HoverCard-container': string
  readonly 'HoverCard-loading--reversed': string
  readonly 'HoverCard-container--large': string
  readonly 'HoverCard-numberBoard': string
  readonly 'HoverCard-buttons': string
  readonly 'HoverCard-numberGroup': string
  readonly 'HoverCard-boardKey': string
  readonly 'HoverCard-boardNumber': string
  readonly 'HoverCard-item': string
  readonly 'HoverCard-description': string
  readonly 'HoverCard-separate': string
  readonly 'HoverCard-popoverTarget': string
  readonly FollowButton: string
  readonly 'FollowButton-icon': string
  readonly 'WalleModal-wrapper': string
  readonly 'WalleModal-des': string
  readonly 'WalleModal-img': string
  readonly 'WalleModal-open': string
  readonly 'WalleModal-content': string
  readonly 'WalleModal-title': string
  readonly 'WalleModal-intro': string
  readonly 'WalleModal-btn': string
  readonly 'Spinner-blade': string
  readonly 'Spinner-blade--large': string
  readonly 'Spinner-blade-12': string
  readonly 'Spinner-blade--white': string
  readonly spinnerBladeFade: string
  readonly TextMessage: string
  readonly 'TextMessage-sender': string
  readonly 'TextMessage-receiver': string
  readonly ImageView: string
  readonly 'ImageView-inner': string
  readonly 'ImageView-img': string
  readonly 'ImageView-transformOrigin': string
  readonly ImageMessage: string
  readonly 'ImageMessage-ImageView': string
  readonly 'ImageMessage--temp': string
  readonly StickerMessage: string
  readonly ActionMenu: string
  readonly 'ActionMenu-item': string
  readonly Message: string
  readonly 'Message--reverse': string
  readonly 'Message-avatar': string
  readonly 'Message-content': string
  readonly 'Message-content--reverse': string
  readonly 'Message-status': string
  readonly 'Message-status--loading': string
  readonly 'Message-status--failure': string
  readonly 'Message-status--more': string
  readonly 'Message-time': string
  readonly 'Message-status--wrapper': string
  readonly 'Message-actionMenu': string
  readonly 'Message-UserLink': string
  readonly 'UserLink-badge': string
  readonly MessagesBox: string
  readonly 'MessagesBox-loading': string
  readonly 'UploadPicture-wrapper': string
  readonly 'UploadPicture-input': string
  readonly EmoticonsFooter: string
  readonly 'EmoticonsFooter-items': string
  readonly 'EmoticonsFooter-item': string
  readonly 'EmoticonsFooter-itemIcon': string
  readonly 'EmoticonsFooter-item--selected': string
  readonly EmoticonPanel: string
  readonly 'EmoticonPanel-item': string
  readonly 'EmoticonPanel-item--big': string
  readonly 'EmoticonPanel-itemImg--small': string
  readonly 'EmoticonPanel-itemImg--big': string
  readonly 'EmoticonPanel-itemTitle': string
  readonly 'EmoticonPanel-spinner': string
  readonly EmoticonPagination: string
  readonly 'EmoticonPagination-bullet': string
  readonly 'EmoticonPagination-bullet--active': string
  readonly Emoticons: string
  readonly 'Emoticons-panels': string
  readonly 'Emoticons-panels-item': string
  readonly 'swiper-wrapper': string
  readonly 'Emoticons-panelContainer': string
  readonly 'Emoticons-Pagination': string
  readonly EmoticonTool: string
  readonly 'EmoticonTool-panel': string
  readonly 'EmoticonTool--mask': string
  readonly 'EmoticonTool-icon': string
  readonly ToolBar: string
  readonly 'ToolBar-item': string
  readonly 'ToolBar-Icon': string
  readonly InputBox: string
  readonly 'InputBox-footer': string
  readonly 'InputBox-input': string
  readonly 'InputBox-sendBtn': string
  readonly 'InputBox-footerDesc': string
  readonly AbnormalAlert: string
  readonly 'AbnormalAlert-message': string
  readonly 'AbnormalAlert-icon': string
  readonly ChatBox: string
  readonly 'ChatBox-title': string
  readonly 'ChatBox-titleVipIcon': string
  readonly 'ChatBox-empty': string
  readonly 'ChatBox-emptyImage': string
  readonly 'ChatBox-emptyDesc': string
  readonly 'ChatBox-alert': string
  readonly 'MessagesBox-wrapper': string
  readonly ChatBoxModal: string
  readonly 'ChatBoxModal-content': string
  readonly 'ChatBoxModal-closeButton': string
  readonly 'ChatBoxModal-closeIcon': string
  readonly MemberButtonGroup: string
  readonly 'MemberButtonGroup-prohibitIcon': string
  readonly FollowStatus: string
  readonly 'UserHoverCard-infoItem': string
  readonly 'UserHoverCard-infoDivider': string
  readonly 'UserHoverCard-mutuals': string
  readonly 'UserHoverCard-orgBadge': string
  readonly 'UserLink-vipIcon': string
  readonly AuthorInfo: string
  readonly 'AuthorInfo-avatar': string
  readonly 'AuthorInfo-content': string
  readonly 'AuthorInfo-head': string
  readonly 'AuthorInfo-name': string
  readonly 'AuthorInfo-badge': string
  readonly 'AuthorInfo-badgeText': string
  readonly 'AuthorInfo--plain': string
  readonly 'AuthorInfo-detail': string
  readonly 'PushNotifications-menu': string
  readonly 'PushNotifications-header': string
  readonly 'PushNotifications-tab': string
  readonly 'PushNotifications-selectedTabIcon': string
  readonly 'PushNotifications-list': string
  readonly 'PushNotifications-item': string
  readonly 'PushNotifications-newItem': string
  readonly 'PushNotifications-followTitle': string
  readonly 'PushNotifications-followItem': string
  readonly 'Notifications-footer': string
  readonly 'PushNotifications-redbot': string
  readonly 'PushNotifications-count': string
  readonly 'PushNotifications-actor': string
  readonly 'Messages-menu': string
  readonly 'Messages-newItem': string
  readonly 'Messages-header': string
  readonly 'Messages-tab': string
  readonly 'Messages-currentTab': string
  readonly 'Messages-myMessageTab': string
  readonly 'Messages-list': string
  readonly 'Messages-withNoTabList': string
  readonly 'Messages-item': string
  readonly 'Messages-user': string
  readonly 'Messages-userName': string
  readonly 'Messages-itemContent': string
  readonly 'Messages-newDialog': string
  readonly 'Messages-footer': string
  readonly 'Messages-receiver': string
  readonly 'Messages-receiverInfo': string
  readonly 'Messages-receiverAutoComplete': string
  readonly 'Messages-records': string
  readonly 'Messages-sendContent': string
  readonly 'Messages-modifyButton': string
  readonly 'Messages-warning': string
  readonly 'Messages-input': string
  readonly 'Messages-icon': string
  readonly 'Messages-count': string
  readonly 'Messages-searchIcon': string
  readonly VagueImage: string
  readonly 'VagueImage-mask': string
  readonly 'VagueImage-innerLarge': string
  readonly LinkCard: string
  readonly 'LinkCard-content': string
  readonly 'LinkCard--noImage': string
  readonly 'LinkCard-text': string
  readonly 'LinkCard-title': string
  readonly 'LinkCard-meta': string
  readonly 'LinkCard-textMeta': string
  readonly 'LinkCard-metaItem': string
  readonly 'LinkCard-metaItem-jobLocation': string
  readonly 'LinkCard-badge': string
  readonly 'LinkCard-image': string
  readonly 'LinkCard-image--horizontal': string
  readonly 'LinkCard-image--vertical': string
  readonly 'LinkCard-imageCell': string
  readonly 'LinkCard--hasImage': string
  readonly 'LinkCard-backdrop': string
  readonly 'LinkCard-image--default': string
  readonly ReferenceList: string
  readonly 'ReferenceList-backHint': string
  readonly 'ReferenceList-backLink': string
  readonly RichText: string
  readonly 'UserLink-link': string
  readonly 'RichText--clearBoth': string
  readonly highlight: string
  readonly hll: string
  readonly c: string
  readonly err: string
  readonly k: string
  readonly o: string
  readonly cm: string
  readonly cp: string
  readonly c1: string
  readonly cs: string
  readonly gd: string
  readonly ge: string
  readonly gr: string
  readonly gh: string
  readonly gi: string
  readonly go: string
  readonly gp: string
  readonly gs: string
  readonly gu: string
  readonly gt: string
  readonly kc: string
  readonly kd: string
  readonly kn: string
  readonly kp: string
  readonly kr: string
  readonly kt: string
  readonly m: string
  readonly s: string
  readonly na: string
  readonly nb: string
  readonly nc: string
  readonly no: string
  readonly ni: string
  readonly ne: string
  readonly nf: string
  readonly nn: string
  readonly nt: string
  readonly nv: string
  readonly ow: string
  readonly w: string
  readonly mf: string
  readonly mh: string
  readonly mi: string
  readonly mo: string
  readonly sb: string
  readonly sc: string
  readonly sd: string
  readonly s2: string
  readonly se: string
  readonly sh: string
  readonly si: string
  readonly sx: string
  readonly sr: string
  readonly s1: string
  readonly ss: string
  readonly bp: string
  readonly vc: string
  readonly vg: string
  readonly vi: string
  readonly il: string
  readonly 'AutoComplete-UserItem': string
  readonly 'AutoComplete-UserDetail': string
  readonly 'AutoComplete-UserHeadline': string
  readonly 'AutoComplete-UserName': string
  readonly 'AutoComplete-UserAvatar': string
  readonly 'AutoComplete-DefaultItem': string
  readonly 'AutoComplete-menu--hidden': string
  readonly 'SearchBar-topSearchItem': string
  readonly 'SearchBar-hotIcon': string
  readonly 'SearchBar-historyItem': string
  readonly 'SearchBar-historyItemContent': string
  readonly blueFont: string
  readonly 'SearchBar-historyLabel': string
  readonly 'SearchBar-historyIconWrapper': string
  readonly 'SearchBar-historyIconShade': string
  readonly 'SearchBar-historyLabelDeleteAll': string
  readonly 'SearchBar-historyDelete': string
  readonly 'SearchBar-historyDeleteAll': string
  readonly AskBrand: string
  readonly 'AskBrand-text': string
  readonly 'AskBrand--list': string
  readonly Tag: string
  readonly 'Tag--removable': string
  readonly 'Tag-remove': string
  readonly TagInputAlias: string
  readonly 'TopicInputAlias-autocomplete': string
  readonly 'TopicInputAlias-input': string
  readonly 'TopicInputAlias-placeholderButton': string
  readonly 'TopicInputAlias-suggestionContainer': string
  readonly 'AskTopics-input': string
  readonly MaxLength: string
  readonly 'is-error': string
  readonly AskFieldTip: string
  readonly 'AskFieldTip--warning': string
  readonly 'AskFieldTip--error': string
  readonly AskTitle: string
  readonly 'AskTitle-text': string
  readonly 'AskTitle-input': string
  readonly 'AskTitle-suggestionClose': string
  readonly 'AskTitle-suggestionPopover': string
  readonly 'AskTitle-suggestionContainer': string
  readonly 'AskTitle-suggestionItem': string
  readonly 'AskTitle-suggestionItemLink': string
  readonly 'AskTitle-suggestionItemDesc': string
  readonly 'Editable-toolbar': string
  readonly isToolbarSticky: string
  readonly 'Editable-toolbar-controls': string
  readonly 'Editable-toolbar-separator': string
  readonly 'Editable-control': string
  readonly 'Editable-toolbarMenu': string
  readonly 'Editable-toolbarMenuItem': string
  readonly EditableToolbarMenuCallout: string
  readonly 'EditableToolbarMenuCallout-closeButton': string
  readonly 'EditableToolbarMenuCallout-arrowBox': string
  readonly AskDetail: string
  readonly 'AskDetail-input': string
  readonly 'AskDetail-inputWrapper': string
  readonly 'AskDetail-actionsWrapper': string
  readonly 'AskDetail-actions': string
  readonly 'AskDetail-placeholder': string
  readonly 'AskOptions-label': string
  readonly 'AskOptions-checkbox': string
  readonly 'AskBrandTitle-main': string
  readonly 'AskBrandTitle-sub': string
  readonly 'Ask-form': string
  readonly 'Ask-items': string
  readonly 'Ask-item': string
  readonly 'Ask-titleWrapper': string
  readonly 'Ask-avatar': string
  readonly 'Ask-title': string
  readonly 'Ask-footer': string
  readonly 'Ask-footer-buttonWrapper': string
  readonly 'Ask-header': string
  readonly 'AskOrgSelect-item': string
  readonly 'AskOrgSelect-itemTitle': string
  readonly 'AskOrgSelect-itemDesc': string
  readonly SearchBar: string
  readonly 'SearchBar-toolWrapper': string
  readonly 'SearchBar-tool': string
  readonly 'SearchBar-groupItem--topSearch': string
  readonly 'SearchBar-groupItem--hisotry': string
  readonly 'SearchBar-menu': string
  readonly 'SearchBar-hasValueMenu': string
  readonly 'AutoComplete-group': string
  readonly 'SearchBar-noValueMenu': string
  readonly 'SearchBar-contentResult': string
  readonly 'SearchBar-defaultResult': string
  readonly 'SearchBar-peopleResult': string
  readonly 'SearchBar-topicResult': string
  readonly 'SearchBar-label': string
  readonly 'SearchBar-label--history': string
  readonly 'SearchBar-userAvatar': string
  readonly 'SearchBar-user': string
  readonly 'SearchBar-userHeadline': string
  readonly 'SearchBar-contentSuffix': string
  readonly 'SearchBar-topicSuffix': string
  readonly 'SearchBar-searchLink': string
  readonly 'SearchBar-askButton': string
  readonly 'SearchBar-hiddenAskButton': string
  readonly 'SearchBar-input': string
  readonly 'SearchBar-focusedInput': string
  readonly 'SearchBar-searchIcon': string
  readonly 'SearchBar-focusedSearchIcon': string
  readonly 'SearchBar-hasValueSearchIcon': string
  readonly 'SearchBar-iconDecorator': string
  readonly 'SearchBar-shownIconDecorator': string
  readonly 'SimpleSearchBar-wrapper': string
  readonly 'SimpleSearchBar-searchButton': string
  readonly 'SimpleSearchBar-input': string
  readonly 'AppHeaderProfileMenu-item': string
  readonly 'AppHeader-profileEntry': string
  readonly 'AppHeader-profileAvatar': string
  readonly 'AppHeader-profileAvatarRedDot': string
  readonly 'AppHeaderProfileMenu-redDot': string
  readonly 'AppHeaderProfileMenu-creatorHintPopover': string
  readonly 'AppHeaderProfileMenu-creatorHintToggler': string
  readonly 'AppHeaderProfileMenu-creatorHintToggler--small': string
  readonly 'AppHeaderProfileMenu-creatorHint': string
  readonly 'AppHeaderProfileMenu-creatorHintCreatorIcon': string
  readonly 'AppHeaderProfileMenu-creatorHintText': string
  readonly 'AppHeaderProfileMenu-creatorHintLink': string
  readonly 'AppHeaderProfileMenu-creatorHintCloseContainer': string
  readonly AppHeader: string
  readonly 'AppHeader-inner': string
  readonly 'AppHeader-Tabs': string
  readonly 'AppHeader-Tab': string
  readonly 'AppHeader-TabsLink': string
  readonly 'AppHeader-navDivider': string
  readonly 'AppHeader-input': string
  readonly 'AppHeader-userInfo': string
  readonly 'AppHeader-messages': string
  readonly 'AppHeader-notifications': string
  readonly 'AppHeader-profile': string
  readonly 'AppHeader-login': string
  readonly 'AppHeader-downloadPopover': string
  readonly 'AppHeader-downloadPopoverImage': string
  readonly AdblockBanner: string
  readonly 'AdblockBanner-inner': string
  readonly 'AdblockBanner-close': string
  readonly 'u-ellipsis': string
  readonly 'App-loginGuideModal': string
  readonly 'App-loginButton': string
  readonly 'App-registerButton': string
  readonly Card: string
  readonly 'Card-header': string
  readonly 'Card-headerText': string
  readonly 'Card-section': string
  readonly SignFlowInput: string
  readonly 'SignFlowInput-errorMask': string
  readonly 'SignFlowInput-errorMask--hidden': string
  readonly 'SignFlowInput-requiredErrorMask': string
  readonly Captcha: string
  readonly 'Captcha-chineseContainer': string
  readonly 'Captcha-englishContainer': string
  readonly 'Captcha-chineseImg': string
  readonly 'Captcha-englishImg': string
  readonly 'Captcha-chineseOperator': string
  readonly 'Captcha-info': string
  readonly 'Captcha-error': string
  readonly 'Captcha-chineseRefreshButton': string
  readonly 'Captcha-errorMessage': string
  readonly 'Captcha-requiredErrorMessage': string
  readonly ChineseCaptchaPoint: string
  readonly 'ChineseCaptchaPoint-backIcon': string
  readonly 'ChineseCaptchaPoint-backIcon--hovered': string
  readonly 'ChineseCaptchaPoint-frontIcon': string
  readonly 'ChineseCaptchaPoint-frontIcon--hovered': string
  readonly MobileContriesSelect: string
  readonly 'MobileContriesSelect-content': string
  readonly 'SignFlow-accountInputContainer': string
  readonly 'SignFlow-account': string
  readonly 'SignFlow-supportedCountriesSelectContainer': string
  readonly 'SignFlow-supportedCountriesList': string
  readonly 'SignFlow-accountSeperator': string
  readonly 'is-counting': string
  readonly 'SignFlow-smsInputContainer': string
  readonly 'SignFlow-smsInputButton': string
  readonly 'SignFlow-smsInputErrorMessage': string
  readonly 'SignFlow-smsInputRequiredErrorMask': string
  readonly 'SignFlow-passwordErrorMask': string
  readonly 'SignFlow-passwordInput': string
  readonly 'SignFlow-requiredPasswordErrorMask': string
  readonly 'SignFlow-password': string
  readonly 'SignFlow-switchPassword': string
  readonly 'SignFlow-switchPasswordIcon': string
  readonly 'SignFlow-username': string
  readonly 'Register-content': string
  readonly 'Register-getIn': string
  readonly 'Register-submitButton': string
  readonly 'Register-footer': string
  readonly 'Register-org': string
  readonly 'Register-declaration': string
  readonly 'Register-padName': string
  readonly 'Register-padNameHeader': string
  readonly 'Register-padNameTitle': string
  readonly 'Register-smsBackUp': string
  readonly 'Register-hiddenSmsBackUp': string
  readonly 'Register-socialHeader': string
  readonly 'Register-socialTitle': string
  readonly 'Register-socialSubTitle': string
  readonly 'Register-socialName': string
  readonly 'Register-hiddenSocialName': string
  readonly SignFlowHeader: string
  readonly 'SignFlowHeader-slogen': string
  readonly 'SignContainer-content': string
  readonly 'Captcha-chinese': string
  readonly 'SignContainer-inner': string
  readonly 'SignContainer-switch': string
  readonly signFlowModal: string
  readonly EmailRegister: string
  readonly 'EmailRegister-submitButton': string
  readonly 'Login-options': string
  readonly 'Login-content': string
  readonly 'Login-footer': string
  readonly 'Login-switchType': string
  readonly 'Login-cannotLogin': string
  readonly 'Login-aboardPhone': string
  readonly 'Login-qrcode': string
  readonly 'Login-footerSeparate': string
  readonly 'Login-socialLogin': string
  readonly 'Login-socialButtonGroup': string
  readonly 'Login-socialButtonGroup--hidden': string
  readonly 'Login-socialButtonEntrance': string
  readonly 'Login-socialButtonEntrance--hidden': string
  readonly 'Login-socialButton': string
  readonly 'Login-accountBlockEmphasis': string
  readonly 'Login-socialIcon': string
  readonly SignInQrcode: string
  readonly 'Qrcode-container': string
  readonly 'Qrcode-scanResultTips': string
  readonly 'Qrcode-content': string
  readonly 'Qrcode-failure': string
  readonly 'Qrcode-img': string
  readonly 'Qrcode-cutButton': string
  readonly 'Qrcode-scanResultStaus': string
  readonly 'SignFlowHomepage-footer': string
  readonly ZhihuIntegrity: string
  readonly 'EntrySign-body': string
  readonly SignFlowHomepage: string
  readonly 'SignFlowHomepage-content': string
  readonly 'SignFlowHomepage-downloadBtn': string
  readonly 'SignFlowHomepage-qrImage': string
  readonly 'SignFlowHomepage-qrImageHidden': string
  readonly OrgCreateButton: string
  readonly 'OrgCreateButton-logoutModal': string
  readonly Footer: string
  readonly 'Footer-dot': string
  readonly 'Footer-item': string
  readonly GlobalWriteAnswerLater: string
  readonly 'GlobalSideBar-navLink': string
  readonly 'GlobalSideBar-navText': string
  readonly 'GlobalWriteAnswerLater-icon': string
  readonly 'GlobalWriteAnswerLater-text': string
  readonly 'GlobalWriteAnswerLater-popover': string
  readonly 'GlobalWriteAnswerLater-popoverText': string
  readonly 'GlobalWrite-card': string
  readonly 'GlobalWrite-nav': string
  readonly 'GlobalWrite-navItem': string
  readonly 'GlobalWrite-navTitle': string
  readonly 'GlobalWrite-navIcon': string
  readonly 'GlobalWrite-draft': string
  readonly 'GlobalWrite-answerTips': string
  readonly 'GlobalSideBar-categoryList': string
  readonly 'GlobalSideBar-categoryItem': string
  readonly 'GlobalSideBar-categoryLabel': string
  readonly 'GlobalSideBar-categoryIcon': string
  readonly 'GlobalSideBar-navList': string
  readonly 'GlobalSideBar-navLink--active': string
  readonly 'GlobalSideBar-navIcon': string
  readonly 'GlobalSideBar-navNumber': string
  readonly 'Pc-card': string
  readonly 'Pc-card--hidden': string
  readonly AdvertImg: string
  readonly 'Pc-card-button-close': string
  readonly 'Pc-card-button-close-svg': string
  readonly 'Banner-adsense': string
  readonly 'Banner-adTag': string
  readonly 'AppBanner-link': string
  readonly 'AppBanner-layout': string
  readonly 'AppBanner-qrcode': string
  readonly 'AppBanner-content': string
  readonly 'AppBanner-title': string
  readonly 'AppBanner-description': string
  readonly 'AppBanner-sticky': string
  readonly AnalyticsCountDelta: string
  readonly 'AnalyticsCountDelta-text': string
  readonly 'AnalyticsCountDelta--small': string
  readonly 'AnalyticsCountDelta-number': string
  readonly 'AnalyticsCountDelta-number--up': string
  readonly 'AnalyticsCountDelta-upIcon': string
  readonly 'AnalyticsCountDelta-number--down': string
  readonly 'AnalyticsCountDelta-downIcon': string
  readonly CreatorEntrance: string
  readonly 'CreatorEntrance-link': string
  readonly 'CreatorEntrance-hint': string
  readonly 'CreatorEntrance-image': string
  readonly 'CreatorEntrance-text': string
  readonly 'CreatorEntrance-title': string
  readonly 'CreatorEntrance-entranceMessage': string
  readonly 'CreatorEntrance-seen': string
  readonly CreatorEntranceShowNew: string
  readonly 'CreatorEntrance-arrow': string
  readonly 'CreatorEntrance-arrow--smallIcon': string
  readonly 'CreatorEntrance-Link--smallIcon': string
  readonly 'CreatorEntrancePage-hint--smallIcon': string
  readonly 'CreatorEntrance-creator': string
  readonly 'CreatorEntrance-indexPageTitle': string
  readonly 'ProfileSideCreator-creatorEntranceHint': string
  readonly 'ProfileSideCreator-analytics': string
  readonly 'ProfileSideCreator-readCountItem': string
  readonly 'ProfileSideCreator-readCountTitle': string
  readonly 'ProfileSideCreator-readCountNumber': string
  readonly 'ProfileSideCreator-readCountDeltaText': string
  readonly 'ProfileSideCreator-analytics--smallIcon': string
  readonly GlobalSideBar: string
  readonly 'NotificationList-DateSplit': string
  readonly 'NotificationList-Item': string
  readonly 'NotificationList-Item--unread': string
  readonly 'NotificationList-Item-header': string
  readonly 'NotificationList-Item-link': string
  readonly 'NotificationList-Item-content': string
  readonly 'NotificationList-Item-extendText': string
  readonly 'NotificationList-Item-icon': string
  readonly 'NotificationList-Item-verb': string
  readonly NotificationList: string
  readonly 'NotificationList-EmptyState': string
  readonly 'NotificationList-DrainedState': string
  readonly List: string
  readonly 'List-header': string
  readonly 'List-headerText': string
  readonly 'List-headerOptions': string
  readonly 'List-loading': string
  readonly 'List-item': string
  readonly 'List-item--holder': string
  readonly 'List-itemMeta': string
  readonly Holder: string
  readonly 'Holder--avatar': string
  readonly 'Holder--button': string
  readonly 'Holder--icon': string
  readonly 'Holder--inline': string
  readonly 'Holder--title': string
  readonly Topbar: string
  readonly 'Topbar-title': string
  readonly 'Topbar--mobile': string
  readonly 'ContentItem-title': string
  readonly 'ContentItem-meta': string
  readonly 'ColumnItem-meta': string
  readonly 'TopicItem-meta': string
  readonly 'ContentItem-avatar': string
  readonly 'UserLink-avatar': string
  readonly 'ContentItem-author': string
  readonly 'ContentItem-status': string
  readonly 'ContentItem-statusItem': string
  readonly 'ContentItem-actions': string
  readonly AnnotationTag: string
  readonly 'ContentItem-action': string
  readonly 'ContentItem-rightButton': string
  readonly 'ContentItem-more': string
  readonly 'ContentItem-time': string
  readonly 'ContentItem-arrowIcon': string
  readonly 'ContentItem-main': string
  readonly 'ContentItem-image': string
  readonly 'ContentItem-head': string
  readonly 'ContentItem-extra': string
  readonly 'ContentItem-cells': string
  readonly 'ContentItem-cell': string
  readonly 'UserItem-avatar': string
  readonly 'UserItem-title': string
  readonly 'UserItem-name': string
  readonly 'UserItem-headline': string
  readonly 'UserItem-business': string
  readonly 'UserItem-company': string
  readonly 'ContentItem-rewardDetails': string
  readonly 'ContentItem-rewardAmount': string
  readonly 'ContentItem-rewardTime': string
  readonly 'Notifications-Layout': string
  readonly 'Notifications-Main': string
  readonly 'Notifications-Section': string
  readonly 'Notifications-Section-header': string
  readonly 'Notifications-Section-header--fixed': string
  readonly 'Notifications-EntryMenu': string
  readonly 'Notifications-MenuItem': string
}
export = styles
